/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as TechniciansRouteImport } from "./routes/technicians";
import { Route as TechnicianRouteImport } from "./routes/technician";
import { Route as SettingsRouteImport } from "./routes/settings";
import { Route as ReportsRouteImport } from "./routes/reports";
import { Route as RegisterRouteImport } from "./routes/register";
import { Route as ProfileRouteImport } from "./routes/profile";
import { Route as PortalRouteImport } from "./routes/portal";
import { Route as PaymentsRouteImport } from "./routes/payments";
import { Route as NotificationsRouteImport } from "./routes/notifications";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as JobsRouteImport } from "./routes/jobs";
import { Route as InvoicesRouteImport } from "./routes/invoices";
import { Route as ForgotPasswordRouteImport } from "./routes/forgot-password";
import { Route as DashboardRouteImport } from "./routes/dashboard";
import { Route as CustomersRouteImport } from "./routes/customers";
import { Route as CalendarRouteImport } from "./routes/calendar";
import { Route as AttendanceRouteImport } from "./routes/attendance";
import { Route as IndexRouteImport } from "./routes/index";

const TechniciansRoute = TechniciansRouteImport.update({
  id: "/technicians",
  path: "/technicians",
  getParentRoute: () => rootRouteImport,
});
const TechnicianRoute = TechnicianRouteImport.update({
  id: "/technician",
  path: "/technician",
  getParentRoute: () => rootRouteImport,
});
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
});
const ReportsRoute = ReportsRouteImport.update({
  id: "/reports",
  path: "/reports",
  getParentRoute: () => rootRouteImport,
});
const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
});
const ProfileRoute = ProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => rootRouteImport,
});
const PortalRoute = PortalRouteImport.update({
  id: "/portal",
  path: "/portal",
  getParentRoute: () => rootRouteImport,
});
const PaymentsRoute = PaymentsRouteImport.update({
  id: "/payments",
  path: "/payments",
  getParentRoute: () => rootRouteImport,
});
const NotificationsRoute = NotificationsRouteImport.update({
  id: "/notifications",
  path: "/notifications",
  getParentRoute: () => rootRouteImport,
});
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
});
const JobsRoute = JobsRouteImport.update({
  id: "/jobs",
  path: "/jobs",
  getParentRoute: () => rootRouteImport,
});
const InvoicesRoute = InvoicesRouteImport.update({
  id: "/invoices",
  path: "/invoices",
  getParentRoute: () => rootRouteImport,
});
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => rootRouteImport,
});
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
});
const CustomersRoute = CustomersRouteImport.update({
  id: "/customers",
  path: "/customers",
  getParentRoute: () => rootRouteImport,
});
const CalendarRoute = CalendarRouteImport.update({
  id: "/calendar",
  path: "/calendar",
  getParentRoute: () => rootRouteImport,
});
const AttendanceRoute = AttendanceRouteImport.update({
  id: "/attendance",
  path: "/attendance",
  getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
});

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendanceRoute: AttendanceRoute,
  CalendarRoute: CalendarRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InvoicesRoute: InvoicesRoute,
  JobsRoute: JobsRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PaymentsRoute: PaymentsRoute,
  PortalRoute: PortalRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TechnicianRoute: TechnicianRoute,
  TechniciansRoute: TechniciansRoute,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes();
