export const technicians = [
  {
    id: "T-01",
    name: "Arjun Mehta",
    role: "Senior HVAC Tech",
    rating: 4.9,
    jobs: 142,
    load: 88,
    status: "On Job",
    avatar: "AM",
    skills: ["HVAC", "Refrigeration"],
  },
  {
    id: "T-02",
    name: "Sneha Iyer",
    role: "Plumbing Lead",
    rating: 4.8,
    jobs: 128,
    load: 65,
    status: "Available",
    avatar: "SI",
    skills: ["Plumbing", "Boilers"],
  },
  {
    id: "T-03",
    name: "Vikram Singh",
    role: "Master Electrician",
    rating: 4.95,
    jobs: 201,
    load: 92,
    status: "On Job",
    avatar: "VS",
    skills: ["Electrical", "Solar"],
  },
  {
    id: "T-04",
    name: "Aisha Patel",
    role: "Appliance Specialist",
    rating: 4.7,
    jobs: 89,
    load: 42,
    status: "Available",
    avatar: "AP",
    skills: ["Appliances"],
  },
  {
    id: "T-05",
    name: "Rohan Verma",
    role: "Field Technician",
    rating: 4.6,
    jobs: 76,
    load: 30,
    status: "Break",
    avatar: "RV",
    skills: ["General"],
  },
  {
    id: "T-06",
    name: "Elena Rodrigues",
    role: "Cleaning Supervisor",
    rating: 4.85,
    jobs: 165,
    load: 70,
    status: "On Job",
    avatar: "ER",
    skills: ["Cleaning"],
  },
  {
    id: "T-07",
    name: "Karan Joshi",
    role: "HVAC Apprentice",
    rating: 4.4,
    jobs: 34,
    load: 55,
    status: "Available",
    avatar: "KJ",
    skills: ["HVAC"],
  },
  {
    id: "T-08",
    name: "Priya Nair",
    role: "Refrigeration Specialist",
    rating: 4.92,
    jobs: 187,
    load: 78,
    status: "On Job",
    avatar: "PN",
    skills: ["Refrigeration"],
  },
];

export const customers = [
  {
    id: "C-1001",
    name: "Sarah Jenkins",
    email: "sarah.j@gmail.com",
    phone: "+91 98450 00142",
    address: "12 MG Road, Bengaluru, KA",
    type: "Residential",
    jobs: 6,
    spent: 235720,
    since: "2023-04-12",
  },
  {
    id: "C-1002",
    name: "Apex Dynamics Ltd.",
    email: "facilities@apexdyn.com",
    phone: "+91 98450 00117",
    address: "501 Brigade Tower, Bengaluru, KA",
    type: "Commercial",
    jobs: 24,
    spent: 1531350,
    since: "2022-09-03",
  },
  {
    id: "C-1003",
    name: "Liam Thompson",
    email: "liam.t@outlook.com",
    phone: "+91 98450 00193",
    address: "98 Indiranagar, Bengaluru, KA",
    type: "Residential",
    jobs: 3,
    spent: 78020,
    since: "2024-01-22",
  },
  {
    id: "C-1004",
    name: "Urban Loft Apartments",
    email: "ops@urbanloft.co",
    phone: "+91 98450 00231",
    address: "2100 Koramangala, Bengaluru, KA",
    type: "Property Mgmt",
    jobs: 41,
    spent: 2664300,
    since: "2021-06-18",
  },
  {
    id: "C-1005",
    name: "Maya Okonkwo",
    email: "maya.o@me.com",
    phone: "+91 98450 00188",
    address: "654 HSR Layout, Bengaluru, KA",
    type: "Residential",
    jobs: 9,
    spent: 350260,
    since: "2023-08-30",
  },
  {
    id: "C-1006",
    name: "Bay Bridge Diner",
    email: "owner@bbdiner.com",
    phone: "+91 98450 00166",
    address: "2400 Whitefield, Bengaluru, KA",
    type: "Commercial",
    jobs: 14,
    spent: 819210,
    since: "2022-11-09",
  },
  {
    id: "C-1007",
    name: "Henry Cho",
    email: "henry@chofamily.net",
    phone: "+91 98450 00177",
    address: "880 Jayanagar, Bengaluru, KA",
    type: "Residential",
    jobs: 2,
    spent: 43160,
    since: "2024-05-04",
  },
  {
    id: "C-1008",
    name: "GreenPath Realty",
    email: "service@greenpath.io",
    phone: "+91 98450 00144",
    address: "1500 Electronic City, Bengaluru, KA",
    type: "Property Mgmt",
    jobs: 33,
    spent: 2048440,
    since: "2022-02-14",
  },
];

export const jobs = [
  {
    id: "JF-9921",
    title: "AC Compressor Replacement",
    customer: "Sarah Jenkins",
    technician: "Arjun Mehta",
    priority: "Critical",
    status: "In Progress",
    scheduled: "Today, 2:30 PM",
    duration: "3h",
    amount: 102920,
  },
  {
    id: "JF-9920",
    title: "Water Heater Install",
    customer: "Apex Dynamics Ltd.",
    technician: "Sneha Iyer",
    priority: "High",
    status: "Assigned",
    scheduled: "Tomorrow, 9:00 AM",
    duration: "4h",
    amount: 178450,
  },
  {
    id: "JF-9919",
    title: "Electrical Panel Inspection",
    customer: "Liam Thompson",
    technician: "Vikram Singh",
    priority: "Medium",
    status: "In Progress",
    scheduled: "Today, 11:00 AM",
    duration: "2h",
    amount: 39840,
  },
  {
    id: "JF-9918",
    title: "Refrigerator Diagnostic",
    customer: "Bay Bridge Diner",
    technician: "Priya Nair",
    priority: "Critical",
    status: "In Progress",
    scheduled: "Today, 9:15 AM",
    duration: "1h",
    amount: 18260,
  },
  {
    id: "JF-9917",
    title: "Drain Cleaning",
    customer: "Urban Loft Apartments",
    technician: "Sneha Iyer",
    priority: "Medium",
    status: "Completed",
    scheduled: "Today, 8:00 AM",
    duration: "1.5h",
    amount: 31540,
  },
  {
    id: "JF-9916",
    title: "Deep Cleaning Service",
    customer: "GreenPath Realty",
    technician: "Elena Rodrigues",
    priority: "Low",
    status: "Completed",
    scheduled: "Today, 7:00 AM",
    duration: "5h",
    amount: 76360,
  },
  {
    id: "JF-9915",
    title: "Heating Tune-Up",
    customer: "Maya Okonkwo",
    technician: "Karan Joshi",
    priority: "Low",
    status: "Pending",
    scheduled: "Fri, 1:00 PM",
    duration: "2h",
    amount: 26560,
  },
  {
    id: "JF-9914",
    title: "Outlet Rewiring",
    customer: "Henry Cho",
    technician: "Vikram Singh",
    priority: "High",
    status: "Assigned",
    scheduled: "Thu, 10:00 AM",
    duration: "3h",
    amount: 53120,
  },
  {
    id: "JF-9913",
    title: "Dishwasher Install",
    customer: "Sarah Jenkins",
    technician: "Aisha Patel",
    priority: "Medium",
    status: "Pending",
    scheduled: "Sat, 11:30 AM",
    duration: "2h",
    amount: 34030,
  },
  {
    id: "JF-9912",
    title: "Boiler Annual Service",
    customer: "Apex Dynamics Ltd.",
    technician: "Sneha Iyer",
    priority: "Medium",
    status: "Completed",
    scheduled: "Yesterday, 3:00 PM",
    duration: "3h",
    amount: 64740,
  },
  {
    id: "JF-9911",
    title: "AC Filter Replacement",
    customer: "Urban Loft Apartments",
    technician: "Arjun Mehta",
    priority: "Low",
    status: "Cancelled",
    scheduled: "Yesterday, 10:00 AM",
    duration: "1h",
    amount: 0,
  },
  {
    id: "JF-9910",
    title: "Emergency Leak Repair",
    customer: "Bay Bridge Diner",
    technician: "Sneha Iyer",
    priority: "Critical",
    status: "Completed",
    scheduled: "Yesterday, 6:00 AM",
    duration: "2h",
    amount: 57270,
  },
];

export const invoices = [
  {
    id: "INV-2024-0419",
    customer: "Apex Dynamics Ltd.",
    job: "JF-9912",
    amount: 64740,
    tax: 5445,
    total: 70185,
    status: "Paid",
    issued: "Oct 18, 2024",
    due: "Nov 01, 2024",
  },
  {
    id: "INV-2024-0418",
    customer: "Bay Bridge Diner",
    job: "JF-9910",
    amount: 57270,
    tax: 4822,
    total: 62092,
    status: "Paid",
    issued: "Oct 17, 2024",
    due: "Oct 31, 2024",
  },
  {
    id: "INV-2024-0417",
    customer: "Urban Loft Apartments",
    job: "JF-9917",
    amount: 31540,
    tax: 2656,
    total: 34196,
    status: "Pending",
    issued: "Oct 19, 2024",
    due: "Nov 02, 2024",
  },
  {
    id: "INV-2024-0416",
    customer: "GreenPath Realty",
    job: "JF-9916",
    amount: 76360,
    tax: 6432,
    total: 82792,
    status: "Pending",
    issued: "Oct 19, 2024",
    due: "Nov 02, 2024",
  },
  {
    id: "INV-2024-0415",
    customer: "Sarah Jenkins",
    job: "JF-9909",
    amount: 26560,
    tax: 2241,
    total: 28801,
    status: "Overdue",
    issued: "Sep 28, 2024",
    due: "Oct 12, 2024",
  },
  {
    id: "INV-2024-0414",
    customer: "Maya Okonkwo",
    job: "JF-9908",
    amount: 44820,
    tax: 3776,
    total: 48596,
    status: "Paid",
    issued: "Oct 12, 2024",
    due: "Oct 26, 2024",
  },
  {
    id: "INV-2024-0413",
    customer: "Apex Dynamics Ltd.",
    job: "JF-9907",
    amount: 178450,
    tax: 15023,
    total: 193473,
    status: "Partial",
    issued: "Oct 10, 2024",
    due: "Oct 24, 2024",
  },
  {
    id: "INV-2024-0412",
    customer: "Henry Cho",
    job: "JF-9906",
    amount: 19920,
    tax: 1660,
    total: 21580,
    status: "Overdue",
    issued: "Sep 22, 2024",
    due: "Oct 06, 2024",
  },
];

export const payments = [
  {
    id: "PAY-9921",
    invoice: "INV-2024-0419",
    customer: "Apex Dynamics Ltd.",
    amount: 70185,
    method: "UPI",
    date: "Oct 22, 2024",
    status: "Completed",
  },
  {
    id: "PAY-9920",
    invoice: "INV-2024-0418",
    customer: "Bay Bridge Diner",
    amount: 62092,
    method: "Credit Card",
    date: "Oct 21, 2024",
    status: "Completed",
  },
  {
    id: "PAY-9919",
    invoice: "INV-2024-0414",
    customer: "Maya Okonkwo",
    amount: 48596,
    method: "Net Banking",
    date: "Oct 20, 2024",
    status: "Completed",
  },
  {
    id: "PAY-9918",
    invoice: "INV-2024-0413",
    customer: "Apex Dynamics Ltd.",
    amount: 83000,
    method: "Bank Transfer",
    date: "Oct 19, 2024",
    status: "Partial",
  },
  {
    id: "PAY-9917",
    invoice: "INV-2024-0411",
    customer: "Urban Loft Apartments",
    amount: 102920,
    method: "Credit Card",
    date: "Oct 17, 2024",
    status: "Completed",
  },
  {
    id: "PAY-9916",
    invoice: "INV-2024-0410",
    customer: "GreenPath Realty",
    amount: 76360,
    method: "Bank Transfer",
    date: "Oct 16, 2024",
    status: "Completed",
  },
];

export const revenueTrend = [
  { day: "Mon", revenue: 348600, jobs: 18 },
  { day: "Tue", revenue: 257300, jobs: 14 },
  { day: "Wed", revenue: 481400, jobs: 22 },
  { day: "Thu", revenue: 365200, jobs: 19 },
  { day: "Fri", revenue: 514600, jobs: 26 },
  { day: "Sat", revenue: 199200, jobs: 11 },
  { day: "Sun", revenue: 448200, jobs: 21 },
];

export const monthlyTrend = [
  { month: "May", revenue: 6972000 },
  { month: "Jun", revenue: 7594500 },
  { month: "Jul", revenue: 8490900 },
  { month: "Aug", revenue: 8192100 },
  { month: "Sep", revenue: 9810600 },
  { month: "Oct", revenue: 11856550 },
];

export const serviceBreakdown = [
  { name: "HVAC", value: 42, color: "hsl(190 90% 60%)" },
  { name: "Plumbing", value: 22, color: "hsl(150 80% 50%)" },
  { name: "Electrical", value: 18, color: "hsl(280 80% 65%)" },
  { name: "Appliances", value: 10, color: "hsl(38 92% 55%)" },
  { name: "Cleaning", value: 8, color: "hsl(340 80% 60%)" },
];

export const notifications = [
  {
    id: 1,
    type: "job",
    title: "New job assigned",
    body: "JF-9921 AC Compressor Replacement assigned to Arjun Mehta",
    time: "4m ago",
    unread: true,
  },
  {
    id: 2,
    type: "payment",
    title: "Payment received",
    body: "Apex Dynamics paid INV-2024-0419 (₹70,185)",
    time: "32m ago",
    unread: true,
  },
  {
    id: 3,
    type: "alert",
    title: "Invoice overdue",
    body: "INV-2024-0415 from Sarah Jenkins is 8 days overdue",
    time: "1h ago",
    unread: true,
  },
  {
    id: 4,
    type: "job",
    title: "Job completed",
    body: "Elena Rodrigues completed JF-9916 Deep Cleaning Service",
    time: "2h ago",
    unread: false,
  },
  {
    id: 5,
    type: "rating",
    title: "New 5-star rating",
    body: "Vikram Singh received a 5★ rating from Liam Thompson",
    time: "3h ago",
    unread: false,
  },
  {
    id: 6,
    type: "system",
    title: "System backup complete",
    body: "Daily backup completed successfully at 03:00 AM",
    time: "8h ago",
    unread: false,
  },
];

export const attendance = [
  {
    id: "A-921",
    tech: "Arjun Mehta",
    date: "Oct 24",
    checkIn: "07:42 AM",
    checkOut: "—",
    hours: "—",
    location: "Indiranagar",
    status: "Active",
  },
  {
    id: "A-920",
    tech: "Sneha Iyer",
    date: "Oct 24",
    checkIn: "08:01 AM",
    checkOut: "—",
    hours: "—",
    location: "Koramangala",
    status: "Active",
  },
  {
    id: "A-919",
    tech: "Vikram Singh",
    date: "Oct 24",
    checkIn: "07:55 AM",
    checkOut: "—",
    hours: "—",
    location: "Whitefield",
    status: "Active",
  },
  {
    id: "A-918",
    tech: "Elena Rodrigues",
    date: "Oct 24",
    checkIn: "06:30 AM",
    checkOut: "11:45 AM",
    hours: "5h 15m",
    location: "HSR Layout",
    status: "Completed",
  },
  {
    id: "A-917",
    tech: "Aisha Patel",
    date: "Oct 24",
    checkIn: "08:15 AM",
    checkOut: "—",
    hours: "—",
    location: "Jayanagar",
    status: "Active",
  },
  {
    id: "A-916",
    tech: "Priya Nair",
    date: "Oct 24",
    checkIn: "07:30 AM",
    checkOut: "—",
    hours: "—",
    location: "MG Road",
    status: "Active",
  },
  {
    id: "A-915",
    tech: "Rohan Verma",
    date: "Oct 24",
    checkIn: "08:45 AM",
    checkOut: "10:00 AM",
    hours: "1h 15m",
    location: "Electronic City",
    status: "On Break",
  },
];

export const statusColors = {
  Pending: "text-muted-foreground bg-muted/40 ring-border",
  Assigned: "text-primary bg-primary/10 ring-primary/20",
  "In Progress": "text-accent bg-accent/10 ring-accent/20",
  Completed: "text-success bg-success/10 ring-success/20",
  Cancelled: "text-destructive bg-destructive/10 ring-destructive/20",
};

export const priorityColors = {
  Critical: "text-destructive bg-destructive/10 ring-destructive/20",
  High: "text-warning bg-warning/10 ring-warning/20",
  Medium: "text-primary bg-primary/10 ring-primary/20",
  Low: "text-muted-foreground bg-muted/40 ring-border",
};
